# Generated by Django 5.2 on 2025-05-13 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userprofile_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lifehack',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_hack', to=settings.AUTH_USER_MODEL),
        ),
    ]
